language: python
python:
  - "3.5"
  - "3.6"
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

notifications:
  email: false

install:
  - pip install -e .[testing]
  - pip install coveralls

script: nosetests --with-coverage --cover-package=wilson

after_success: coveralls
